# .PHONY: clean

# $TARGET = bootloader
# $LINKER = linker.ld

# all: $(TARGET).img
	
# %.img: %.elf
# 	$(OBJCOPY) -O binary $< $@

# %.elf: $(LINKER) $(OBJS)
# 	$(LD) -T $(LINKER) $(LDFLAGS) -o $@ $(OBJS)
